// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.ntuc.income.up.model;

public final class RegisterOuterClass {
  private RegisterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Register)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstName = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string emailOrMobile = 3;</code>
     */
    java.lang.String getEmailOrMobile();
    /**
     * <code>string emailOrMobile = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailOrMobileBytes();

    /**
     * <code>string signUpPassword = 4;</code>
     */
    java.lang.String getSignUpPassword();
    /**
     * <code>string signUpPassword = 4;</code>
     */
    com.google.protobuf.ByteString
        getSignUpPasswordBytes();
  }
  /**
   * Protobuf type {@code model.Register}
   */
  public  static final class Register extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Register)
      RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Register() {
      firstName_ = "";
      lastName_ = "";
      emailOrMobile_ = "";
      signUpPassword_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              emailOrMobile_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              signUpPassword_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ntuc.income.up.model.RegisterOuterClass.Register.class, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder.class);
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILORMOBILE_FIELD_NUMBER = 3;
    private volatile java.lang.Object emailOrMobile_;
    /**
     * <code>string emailOrMobile = 3;</code>
     */
    public java.lang.String getEmailOrMobile() {
      java.lang.Object ref = emailOrMobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailOrMobile_ = s;
        return s;
      }
    }
    /**
     * <code>string emailOrMobile = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailOrMobileBytes() {
      java.lang.Object ref = emailOrMobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailOrMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNUPPASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object signUpPassword_;
    /**
     * <code>string signUpPassword = 4;</code>
     */
    public java.lang.String getSignUpPassword() {
      java.lang.Object ref = signUpPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signUpPassword_ = s;
        return s;
      }
    }
    /**
     * <code>string signUpPassword = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignUpPasswordBytes() {
      java.lang.Object ref = signUpPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signUpPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getEmailOrMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emailOrMobile_);
      }
      if (!getSignUpPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signUpPassword_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getEmailOrMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emailOrMobile_);
      }
      if (!getSignUpPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signUpPassword_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ntuc.income.up.model.RegisterOuterClass.Register)) {
        return super.equals(obj);
      }
      com.ntuc.income.up.model.RegisterOuterClass.Register other = (com.ntuc.income.up.model.RegisterOuterClass.Register) obj;

      boolean result = true;
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getEmailOrMobile()
          .equals(other.getEmailOrMobile());
      result = result && getSignUpPassword()
          .equals(other.getSignUpPassword());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAILORMOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getEmailOrMobile().hashCode();
      hash = (37 * hash) + SIGNUPPASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getSignUpPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ntuc.income.up.model.RegisterOuterClass.Register prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Register}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Register)
        com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ntuc.income.up.model.RegisterOuterClass.Register.class, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder.class);
      }

      // Construct using com.ntuc.income.up.model.RegisterOuterClass.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        emailOrMobile_ = "";

        signUpPassword_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Register_descriptor;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstanceForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance();
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register build() {
        com.ntuc.income.up.model.RegisterOuterClass.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Register buildPartial() {
        com.ntuc.income.up.model.RegisterOuterClass.Register result = new com.ntuc.income.up.model.RegisterOuterClass.Register(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.emailOrMobile_ = emailOrMobile_;
        result.signUpPassword_ = signUpPassword_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ntuc.income.up.model.RegisterOuterClass.Register) {
          return mergeFrom((com.ntuc.income.up.model.RegisterOuterClass.Register)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ntuc.income.up.model.RegisterOuterClass.Register other) {
        if (other == com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmailOrMobile().isEmpty()) {
          emailOrMobile_ = other.emailOrMobile_;
          onChanged();
        }
        if (!other.getSignUpPassword().isEmpty()) {
          signUpPassword_ = other.signUpPassword_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ntuc.income.up.model.RegisterOuterClass.Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ntuc.income.up.model.RegisterOuterClass.Register) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emailOrMobile_ = "";
      /**
       * <code>string emailOrMobile = 3;</code>
       */
      public java.lang.String getEmailOrMobile() {
        java.lang.Object ref = emailOrMobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emailOrMobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emailOrMobile = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailOrMobileBytes() {
        java.lang.Object ref = emailOrMobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emailOrMobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emailOrMobile = 3;</code>
       */
      public Builder setEmailOrMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emailOrMobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emailOrMobile = 3;</code>
       */
      public Builder clearEmailOrMobile() {
        
        emailOrMobile_ = getDefaultInstance().getEmailOrMobile();
        onChanged();
        return this;
      }
      /**
       * <code>string emailOrMobile = 3;</code>
       */
      public Builder setEmailOrMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emailOrMobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signUpPassword_ = "";
      /**
       * <code>string signUpPassword = 4;</code>
       */
      public java.lang.String getSignUpPassword() {
        java.lang.Object ref = signUpPassword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signUpPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signUpPassword = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSignUpPasswordBytes() {
        java.lang.Object ref = signUpPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signUpPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signUpPassword = 4;</code>
       */
      public Builder setSignUpPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signUpPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signUpPassword = 4;</code>
       */
      public Builder clearSignUpPassword() {
        
        signUpPassword_ = getDefaultInstance().getSignUpPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string signUpPassword = 4;</code>
       */
      public Builder setSignUpPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signUpPassword_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:model.Register)
    }

    // @@protoc_insertion_point(class_scope:model.Register)
    private static final com.ntuc.income.up.model.RegisterOuterClass.Register DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ntuc.income.up.model.RegisterOuterClass.Register();
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Register>
        PARSER = new com.google.protobuf.AbstractParser<Register>() {
      public Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Register(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Register> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Register> getParserForType() {
      return PARSER;
    }

    public com.ntuc.income.up.model.RegisterOuterClass.Register getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegistersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Registers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> 
        getRegistersList();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index);
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    int getRegistersCount();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
        getRegistersOrBuilderList();
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.Registers}
   */
  public  static final class Registers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Registers)
      RegistersOrBuilder {
    // Use Registers.newBuilder() to construct.
    private Registers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Registers() {
      registers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Registers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                registers_ = new java.util.ArrayList<com.ntuc.income.up.model.RegisterOuterClass.Register>();
                mutable_bitField0_ |= 0x00000001;
              }
              registers_.add(
                  input.readMessage(com.ntuc.income.up.model.RegisterOuterClass.Register.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          registers_ = java.util.Collections.unmodifiableList(registers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ntuc.income.up.model.RegisterOuterClass.Registers.class, com.ntuc.income.up.model.RegisterOuterClass.Registers.Builder.class);
    }

    public static final int REGISTERS_FIELD_NUMBER = 1;
    private java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> registers_;
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> getRegistersList() {
      return registers_;
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
        getRegistersOrBuilderList() {
      return registers_;
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public int getRegistersCount() {
      return registers_.size();
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index) {
      return registers_.get(index);
    }
    /**
     * <code>repeated .model.Register registers = 1;</code>
     */
    public com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
        int index) {
      return registers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < registers_.size(); i++) {
        output.writeMessage(1, registers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < registers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, registers_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ntuc.income.up.model.RegisterOuterClass.Registers)) {
        return super.equals(obj);
      }
      com.ntuc.income.up.model.RegisterOuterClass.Registers other = (com.ntuc.income.up.model.RegisterOuterClass.Registers) obj;

      boolean result = true;
      result = result && getRegistersList()
          .equals(other.getRegistersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRegistersCount() > 0) {
        hash = (37 * hash) + REGISTERS_FIELD_NUMBER;
        hash = (53 * hash) + getRegistersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ntuc.income.up.model.RegisterOuterClass.Registers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ntuc.income.up.model.RegisterOuterClass.Registers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Registers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Registers)
        com.ntuc.income.up.model.RegisterOuterClass.RegistersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ntuc.income.up.model.RegisterOuterClass.Registers.class, com.ntuc.income.up.model.RegisterOuterClass.Registers.Builder.class);
      }

      // Construct using com.ntuc.income.up.model.RegisterOuterClass.Registers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRegistersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (registersBuilder_ == null) {
          registers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          registersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.internal_static_model_Registers_descriptor;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstanceForType() {
        return com.ntuc.income.up.model.RegisterOuterClass.Registers.getDefaultInstance();
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers build() {
        com.ntuc.income.up.model.RegisterOuterClass.Registers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ntuc.income.up.model.RegisterOuterClass.Registers buildPartial() {
        com.ntuc.income.up.model.RegisterOuterClass.Registers result = new com.ntuc.income.up.model.RegisterOuterClass.Registers(this);
        int from_bitField0_ = bitField0_;
        if (registersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            registers_ = java.util.Collections.unmodifiableList(registers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.registers_ = registers_;
        } else {
          result.registers_ = registersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ntuc.income.up.model.RegisterOuterClass.Registers) {
          return mergeFrom((com.ntuc.income.up.model.RegisterOuterClass.Registers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ntuc.income.up.model.RegisterOuterClass.Registers other) {
        if (other == com.ntuc.income.up.model.RegisterOuterClass.Registers.getDefaultInstance()) return this;
        if (registersBuilder_ == null) {
          if (!other.registers_.isEmpty()) {
            if (registers_.isEmpty()) {
              registers_ = other.registers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRegistersIsMutable();
              registers_.addAll(other.registers_);
            }
            onChanged();
          }
        } else {
          if (!other.registers_.isEmpty()) {
            if (registersBuilder_.isEmpty()) {
              registersBuilder_.dispose();
              registersBuilder_ = null;
              registers_ = other.registers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              registersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRegistersFieldBuilder() : null;
            } else {
              registersBuilder_.addAllMessages(other.registers_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ntuc.income.up.model.RegisterOuterClass.Registers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ntuc.income.up.model.RegisterOuterClass.Registers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> registers_ =
        java.util.Collections.emptyList();
      private void ensureRegistersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          registers_ = new java.util.ArrayList<com.ntuc.income.up.model.RegisterOuterClass.Register>(registers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> registersBuilder_;

      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register> getRegistersList() {
        if (registersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(registers_);
        } else {
          return registersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public int getRegistersCount() {
        if (registersBuilder_ == null) {
          return registers_.size();
        } else {
          return registersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register getRegisters(int index) {
        if (registersBuilder_ == null) {
          return registers_.get(index);
        } else {
          return registersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder setRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.set(index, value);
          onChanged();
        } else {
          registersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder setRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.set(index, builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.add(value);
          onChanged();
        } else {
          registersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register value) {
        if (registersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegistersIsMutable();
          registers_.add(index, value);
          onChanged();
        } else {
          registersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.add(builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addRegisters(
          int index, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder builderForValue) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.add(index, builderForValue.build());
          onChanged();
        } else {
          registersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder addAllRegisters(
          java.lang.Iterable<? extends com.ntuc.income.up.model.RegisterOuterClass.Register> values) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, registers_);
          onChanged();
        } else {
          registersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder clearRegisters() {
        if (registersBuilder_ == null) {
          registers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          registersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public Builder removeRegisters(int index) {
        if (registersBuilder_ == null) {
          ensureRegistersIsMutable();
          registers_.remove(index);
          onChanged();
        } else {
          registersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder getRegistersBuilder(
          int index) {
        return getRegistersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder getRegistersOrBuilder(
          int index) {
        if (registersBuilder_ == null) {
          return registers_.get(index);  } else {
          return registersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<? extends com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
           getRegistersOrBuilderList() {
        if (registersBuilder_ != null) {
          return registersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(registers_);
        }
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder addRegistersBuilder() {
        return getRegistersFieldBuilder().addBuilder(
            com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public com.ntuc.income.up.model.RegisterOuterClass.Register.Builder addRegistersBuilder(
          int index) {
        return getRegistersFieldBuilder().addBuilder(
            index, com.ntuc.income.up.model.RegisterOuterClass.Register.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Register registers = 1;</code>
       */
      public java.util.List<com.ntuc.income.up.model.RegisterOuterClass.Register.Builder> 
           getRegistersBuilderList() {
        return getRegistersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder> 
          getRegistersFieldBuilder() {
        if (registersBuilder_ == null) {
          registersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ntuc.income.up.model.RegisterOuterClass.Register, com.ntuc.income.up.model.RegisterOuterClass.Register.Builder, com.ntuc.income.up.model.RegisterOuterClass.RegisterOrBuilder>(
                  registers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          registers_ = null;
        }
        return registersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:model.Registers)
    }

    // @@protoc_insertion_point(class_scope:model.Registers)
    private static final com.ntuc.income.up.model.RegisterOuterClass.Registers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ntuc.income.up.model.RegisterOuterClass.Registers();
    }

    public static com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Registers>
        PARSER = new com.google.protobuf.AbstractParser<Registers>() {
      public Registers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Registers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Registers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Registers> getParserForType() {
      return PARSER;
    }

    public com.ntuc.income.up.model.RegisterOuterClass.Registers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Register_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Register_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Registers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Registers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016register.proto\022\005model\"^\n\010Register\022\021\n\tf" +
      "irstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022\025\n\remai" +
      "lOrMobile\030\003 \001(\t\022\026\n\016signUpPassword\030\004 \001(\t\"" +
      "/\n\tRegisters\022\"\n\tregisters\030\001 \003(\0132\017.model." +
      "RegisterB\032\n\030com.ntuc.income.up.modelb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_Register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Register_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "EmailOrMobile", "SignUpPassword", });
    internal_static_model_Registers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_Registers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Registers_descriptor,
        new java.lang.String[] { "Registers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
